import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Movies App",
//   description: "Generated by create next app",
//   icons: {
//     icon: "/star.svg", // Standard favicon
//   },
// };

export const metadata: Metadata = {
  title: "Robot Control Dashboard",
  description: "Generated by create next app",
  icons: {
     icon: "/robotic-arm.svg", // Standard favicon
   }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
